'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class RecursoLenguajeENG
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("sigesi.RecursoLenguajeENG", GetType(RecursoLenguajeENG).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend Shared ReadOnly Property btnAgregar() As String
            Get
                Return ResourceManager.GetString("btnAgregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend Shared ReadOnly Property btnAlta() As String
            Get
                Return ResourceManager.GetString("btnAlta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Student.
        '''</summary>
        Friend Shared ReadOnly Property btnAlumno() As String
            Get
                Return ResourceManager.GetString("btnAlumno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Back.
        '''</summary>
        Friend Shared ReadOnly Property btnAtras() As String
            Get
                Return ResourceManager.GetString("btnAtras", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drop.
        '''</summary>
        Friend Shared ReadOnly Property btnBaja() As String
            Get
                Return ResourceManager.GetString("btnBaja", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property btnBuscar() As String
            Get
                Return ResourceManager.GetString("btnBuscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property btnCancelar() As String
            Get
                Return ResourceManager.GetString("btnCancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close Session.
        '''</summary>
        Friend Shared ReadOnly Property btnCerrarSesion() As String
            Get
                Return ResourceManager.GetString("btnCerrarSesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Building.
        '''</summary>
        Friend Shared ReadOnly Property btnEdificio() As String
            Get
                Return ResourceManager.GetString("btnEdificio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove.
        '''</summary>
        Friend Shared ReadOnly Property btnEliminar() As String
            Get
                Return ResourceManager.GetString("btnEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter.
        '''</summary>
        Friend Shared ReadOnly Property btnEntrar() As String
            Get
                Return ResourceManager.GetString("btnEntrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Report Management.
        '''</summary>
        Friend Shared ReadOnly Property btnGestionInformes() As String
            Get
                Return ResourceManager.GetString("btnGestionInformes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group.
        '''</summary>
        Friend Shared ReadOnly Property btnGrupo() As String
            Get
                Return ResourceManager.GetString("btnGrupo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to incidents.
        '''</summary>
        Friend Shared ReadOnly Property btnIncidencias() As String
            Get
                Return ResourceManager.GetString("btnIncidencias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start.
        '''</summary>
        Friend Shared ReadOnly Property btnInicio() As String
            Get
                Return ResourceManager.GetString("btnInicio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subject.
        '''</summary>
        Friend Shared ReadOnly Property btnMateria() As String
            Get
                Return ResourceManager.GetString("btnMateria", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subject by Group.
        '''</summary>
        Friend Shared ReadOnly Property btnMateriaGrupo() As String
            Get
                Return ResourceManager.GetString("btnMateriaGrupo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modify.
        '''</summary>
        Friend Shared ReadOnly Property btnModificar() As String
            Get
                Return ResourceManager.GetString("btnModificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reports.
        '''</summary>
        Friend Shared ReadOnly Property btnReportes() As String
            Get
                Return ResourceManager.GetString("btnReportes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Classrooms.
        '''</summary>
        Friend Shared ReadOnly Property btnSalones() As String
            Get
                Return ResourceManager.GetString("btnSalones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Users.
        '''</summary>
        Friend Shared ReadOnly Property btnUsuario() As String
            Get
                Return ResourceManager.GetString("btnUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search student.
        '''</summary>
        Friend Shared ReadOnly Property gpbBuscarAlumnos() As String
            Get
                Return ResourceManager.GetString("gpbBuscarAlumnos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search incident.
        '''</summary>
        Friend Shared ReadOnly Property gpbBuscarIncidencia() As String
            Get
                Return ResourceManager.GetString("gpbBuscarIncidencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search inscription.
        '''</summary>
        Friend Shared ReadOnly Property gpbBuscarInscripciones() As String
            Get
                Return ResourceManager.GetString("gpbBuscarInscripciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administrative.
        '''</summary>
        Friend Shared ReadOnly Property lblAdministrativo() As String
            Get
                Return ResourceManager.GetString("lblAdministrativo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System administrator.
        '''</summary>
        Friend Shared ReadOnly Property lblAdminSist() As String
            Get
                Return ResourceManager.GetString("lblAdminSist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Student.
        '''</summary>
        Friend Shared ReadOnly Property lblAlumno() As String
            Get
                Return ResourceManager.GetString("lblAlumno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Surname.
        '''</summary>
        Friend Shared ReadOnly Property lblApe() As String
            Get
                Return ResourceManager.GetString("lblApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To modify, select a building from the list.
        '''</summary>
        Friend Shared ReadOnly Property lblAyudaModificarEdificio() As String
            Get
                Return ResourceManager.GetString("lblAyudaModificarEdificio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To modify, select a group from the list.
        '''</summary>
        Friend Shared ReadOnly Property lblAyudaModificarGrupo() As String
            Get
                Return ResourceManager.GetString("lblAyudaModificarGrupo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To modify, select a user from the list.
        '''</summary>
        Friend Shared ReadOnly Property lblAyudaModificarUsuario() As String
            Get
                Return ResourceManager.GetString("lblAyudaModificarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Identity card.
        '''</summary>
        Friend Shared ReadOnly Property lblCi() As String
            Get
                Return ResourceManager.GetString("lblCi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code.
        '''</summary>
        Friend Shared ReadOnly Property lblCod() As String
            Get
                Return ResourceManager.GetString("lblCod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Course.
        '''</summary>
        Friend Shared ReadOnly Property lblCurso() As String
            Get
                Return ResourceManager.GetString("lblCurso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to description.
        '''</summary>
        Friend Shared ReadOnly Property lblDesc() As String
            Get
                Return ResourceManager.GetString("lblDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address.
        '''</summary>
        Friend Shared ReadOnly Property lblDir() As String
            Get
                Return ResourceManager.GetString("lblDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Director.
        '''</summary>
        Friend Shared ReadOnly Property lblDirector() As String
            Get
                Return ResourceManager.GetString("lblDirector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Teacher.
        '''</summary>
        Friend Shared ReadOnly Property lblDocente() As String
            Get
                Return ResourceManager.GetString("lblDocente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Building.
        '''</summary>
        Friend Shared ReadOnly Property lblEdificio() As String
            Get
                Return ResourceManager.GetString("lblEdificio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E-mail.
        '''</summary>
        Friend Shared ReadOnly Property lblEmail() As String
            Get
                Return ResourceManager.GetString("lblEmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Group.
        '''</summary>
        Friend Shared ReadOnly Property lblGrupo() As String
            Get
                Return ResourceManager.GetString("lblGrupo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to list incidents.
        '''</summary>
        Friend Shared ReadOnly Property lblListaIncidencia() As String
            Get
                Return ResourceManager.GetString("lblListaIncidencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subject.
        '''</summary>
        Friend Shared ReadOnly Property lblMateria() As String
            Get
                Return ResourceManager.GetString("lblMateria", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Name.
        '''</summary>
        Friend Shared ReadOnly Property lblNom() As String
            Get
                Return ResourceManager.GetString("lblNom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Second Name.
        '''</summary>
        Friend Shared ReadOnly Property lblNom1() As String
            Get
                Return ResourceManager.GetString("lblNom1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property lblPwd() As String
            Get
                Return ResourceManager.GetString("lblPwd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Roll.
        '''</summary>
        Friend Shared ReadOnly Property lblRoll() As String
            Get
                Return ResourceManager.GetString("lblRoll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose your type of user.
        '''</summary>
        Friend Shared ReadOnly Property lblSelecUsu() As String
            Get
                Return ResourceManager.GetString("lblSelecUsu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone.
        '''</summary>
        Friend Shared ReadOnly Property lblTel() As String
            Get
                Return ResourceManager.GetString("lblTel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Build.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloAltaEdificio() As String
            Get
                Return ResourceManager.GetString("lblTituloAltaEdificio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Group.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloAltaGrupo() As String
            Get
                Return ResourceManager.GetString("lblTituloAltaGrupo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Incident.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloAltaIncidencia() As String
            Get
                Return ResourceManager.GetString("lblTituloAltaIncidencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add subject to group.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloAltaMateriaGrupo() As String
            Get
                Return ResourceManager.GetString("lblTituloAltaMateriaGrupo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add User.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloAltaUsuario() As String
            Get
                Return ResourceManager.GetString("lblTituloAltaUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Build.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloBajaEdificio() As String
            Get
                Return ResourceManager.GetString("lblTituloBajaEdificio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete Group.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloBajaGrupo() As String
            Get
                Return ResourceManager.GetString("lblTituloBajaGrupo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drop Subject.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloBajaMateria() As String
            Get
                Return ResourceManager.GetString("lblTituloBajaMateria", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove matter from a group.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloBajaMateriaGrupo() As String
            Get
                Return ResourceManager.GetString("lblTituloBajaMateriaGrupo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete User.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloBajaUsuario() As String
            Get
                Return ResourceManager.GetString("lblTituloBajaUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administrative.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloHomeAdministrativo() As String
            Get
                Return ResourceManager.GetString("lblTituloHomeAdministrativo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System administrator.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloHomeAdminSistema() As String
            Get
                Return ResourceManager.GetString("lblTituloHomeAdminSistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attached teacher.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloHomeBedel() As String
            Get
                Return ResourceManager.GetString("lblTituloHomeBedel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Director.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloHomeDirector() As String
            Get
                Return ResourceManager.GetString("lblTituloHomeDirector", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modify Build.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloModificarEdificio() As String
            Get
                Return ResourceManager.GetString("lblTituloModificarEdificio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Updare Group.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloModificarGrupo() As String
            Get
                Return ResourceManager.GetString("lblTituloModificarGrupo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Update User.
        '''</summary>
        Friend Shared ReadOnly Property lblTituloModificarUsuario() As String
            Get
                Return ResourceManager.GetString("lblTituloModificarUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn.
        '''</summary>
        Friend Shared ReadOnly Property lblTurno() As String
            Get
                Return ResourceManager.GetString("lblTurno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Friend Shared ReadOnly Property lblUsu() As String
            Get
                Return ResourceManager.GetString("lblUsu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year.
        '''</summary>
        Friend Shared ReadOnly Property lblYear() As String
            Get
                Return ResourceManager.GetString("lblYear", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
